#cloud-config

apt_sources:
  - source: "ppa:gns3/ppa"
  
packages:
  # Guacamole dependencies
  - vim
  - nano
  - curl
  - wget
  - libcairo2-dev
  - libjpeg-turbo8-dev
  - libpng-dev
  - libtool-bin
  - libossp-uuid-dev
  - libavcodec-dev
  - libavutil-dev
  - libswscale-dev
  - build-essential
  - libvncserver-dev
  - libtelnet-dev
  - libssl-dev
  - libwebp-dev
  - openjdk-11-jdk
  - tomcat9

  # Desktop
  - xserver-xorg-core
  - openbox
  - lxpanel
  - xcompmgr
  - pcmanfm
  - midori
  - xinit
  - slim

  # GNS3
  - gns3-server
  - gns3-gui

write_files:
  - content: |
      [Unit]
      Description=Tomcat 9 servlet container
      After=network.target

      [Service]
      Type=forking

      User=tomcat
      Group=tomcat

      Environment="JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"
      Environment="JAVA_OPTS=-Djava.security.egd=file:///dev/urandom -Djava.awt.headless=true"

      Environment="CATALINA_BASE=/opt/tomcat/tomcatapp"
      Environment="CATALINA_HOME=/opt/tomcat/tomcatapp"
      Environment="CATALINA_PID=/opt/tomcat/tomcatapp/temp/tomcat.pid"
      Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"

      ExecStart=/opt/tomcat/tomcatapp/bin/startup.sh
      ExecStop=/opt/tomcat/tomcatapp/bin/shutdown.sh

      [Install]
      WantedBy=multi-user.target
    path: /etc/systemd/system/tomcat.service

  - content: |
      guacd-hostname: localhost
      guacd-port:    4822
      user-mapping:    /etc/guacamole/user-mapping.xml
      auth-provider:    net.sourceforge.guacamole.net.basic.BasicFileAuthenticationProvider
    path: /etc/guacamole/guacamole.properties

  - content: |
      <user-mapping>
          <authorize username="admin"
                  password="51a12666ba6ba69e453bc08fa3c5c8a9"
                  encoding="md5"> <connection name="Ubuntu20.04-Server">
                  <protocol>SSH</protocol>
                  <param name="hostname">localhost</param>
                  <param name="port">22</param>
                  <param name="username">root</param>
              </connection>
              <connection name="VNC">
                  <protocol>vnc</protocol>
                  <param name="hostname">localhost</param>
                  <param name="port">5900</param>
                  <param name="username">vagrant</param>
              </connection>
          </authorize>
      </user-mapping>
    path: /etc/guacamole/user-mapping.xml

# TODO GNS3 config
# TODO VNC config

runcmd:
 - export DEBIAN_FRONTEND=noninteractive

 # Guacamole
 - wget https://downloads.apache.org/guacamole/1.3.0/source/guacamole-server-1.3.0.tar.gz -P /home/ubuntu
 - tar xzf /home/ubuntu/guacamole-server-1.3.0.tar.gz
 - cd /home/ubuntu/guacamole-server-1.3.0
 - ./configure --with-init-dir=/etc/init.d
 - make
 - make install
 - ldconfig
 - systemctl daemon-reload
 - systemctl start guacd
 - systemctl enable guacd

 - mkdir /etc/guacamole
 - wget https://downloads.apache.org/guacamole/1.3.0/binary/guacamole-1.3.0.war -P /home/ubuntu
 - mv /home/ubuntu/guacamole-1.3.0.war /etc/guacamole/guacamole.war

 - ln -s /etc/guacamole/guacamole.war /var/lib/tomcat9/webapps/
 - echo "GUACAMOLE_HOME=/etc/guacamole" | sudo tee -a /etc/default/tomcat
 - ln -s /etc/guacamole /var/lib/tomcat9/webapps/.guacamole

 - systemctl restart tomcat guacd
 - ufw allow 4822/tcp

 - sed -i '70s/.*/default_user ubuntu/' /etc/slim.conf
 - sed -i '78s/.*/auto_login yes/' /etc/slim.conf
