#cloud-config
apt-sources:
 - source: "ppa:gns3/ppa"

packages:
 - vim
 - curl 
 - wget
 - libcairo2-dev 
 - libjpeg-turbo8-dev 
 - libpng-dev 
 - libtool-bin
 - libossp-uuid-dev
 - libavcodec-dev
 - libavutil-dev
 - libswscale-dev
 - build-essential
 - libvncserver-dev
 - libtelnet-dev
 - libssl-dev
 - libwebp-dev
 - openjdk-11-jdk
 - tomcat9
 - openbox
 - lxpanel
 - gns3-server=2.2.27
 - gns3-gui=2.2.27