#cloud-config

apt_sources:
  - source: "ppa:gns3/ppa"
  
packages:
  # Guacamole dependencies
  - vim
  - nano
  - curl
  - wget
  - libcairo2-dev
  - libjpeg-turbo8-dev
  - libpng-dev
  - libtool-bin
  - libossp-uuid-dev
  - libavcodec-dev
  - libavutil-dev
  - libswscale-dev
  - build-essential
  - libvncserver-dev
  - libtelnet-dev
  - libssl-dev
  - libwebp-dev
  - openjdk-11-jdk
  - tomcat9

  # Desktop
  - xserver-xorg-core
  - openbox
  - lxpanel
  - xcompmgr
  - pcmanfm
  - midori
  - xinit
  - slim

  # GNS3
  - gns3-server
  - gns3-gui

write_files:
  - content: |
      [Unit]
      Description=Tomcat 9 servlet container
      After=network.target

      [Service]
      Type=forking

      User=tomcat
      Group=tomcat

      Environment="JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"
      Environment="JAVA_OPTS=-Djava.security.egd=file:///dev/urandom -Djava.awt.headless=true"

      Environment="CATALINA_BASE=/opt/tomcat/tomcatapp"
      Environment="CATALINA_HOME=/opt/tomcat/tomcatapp"
      Environment="CATALINA_PID=/opt/tomcat/tomcatapp/temp/tomcat.pid"
      Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"

      ExecStart=/opt/tomcat/tomcatapp/bin/startup.sh
      ExecStop=/opt/tomcat/tomcatapp/bin/shutdown.sh

      [Install]
      WantedBy=multi-user.target
    path: /etc/systemd/system/tomcat.service

# TODO Guacamole
# TODO GNS3 config
# TODO VNC config

runcmd:
 # Default passwords
 - export GUACAMOLE_ADMIN_PASSWORD=Ge5L0
 - export VNC_CONNECTION_PASSWORD=GNS3JeZ4k0n
 
 - export GUACAMOLE_ADMIN_PASSWORD_HASH=$(echo -n $GUACAMOLE_ADMIN_PASSWORD | openssl md5 | awk '{print $NF}')
 - export DEBIAN_FRONTEND=noninteractive
